apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o362ctywl-python 
  janus-idp.io/tekton: o362ctywl-python
  backstage.io/kubernetes-id: o362ctywl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o362ctywl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml